sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull
   
   
# command to run tests
script: cd src/envo && make travis_test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov

